import Head from 'next/head'
import conectarDB from '../lib/dbConnection';
import Movie from '../models/Movies'; 
import Link from 'next/link';


export default function Home({movies}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
       <h1>movies</h1>
       <Link href={"/new"} className={"btn btn-info w-100 mb-2"}>
        Agregar
       </Link>

       {
        movies.map(({_id, title, plot})=>{

          return(
            <div className='card mb-2' key={_id}>
              <div className='card-body'>
                <div className='h5 text-uppercase'>{title}</div>
                <p className='fw-ligth'>{plot}</p>
                <Link href={`/${_id}`} className="btn btn-success btn-xs m-2">Mas info...</Link>
              </div>

            </div>
          )
          
        })
       }
      </main>
    </div>
  )
}

export const getServerSideProps = async () => {
  try {
    await conectarDB();
    const res= await Movie.find({});
    const movies = res.map(doc=>{
      const movie = doc.toObject();
      movie._id = `${movie._id}`;
      return movie
    })
    return {props:{movies}}
    
  } catch (error) {
    console.log(error)
    return { props: { success: false, error: "error en el servicio" } }
  }
  
}